# Generated by Django 4.2.15 on 2024-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="feespaid",
            new_name="paidfees",
        ),
    ]
